drop extension if exists "pg_net";

drop policy "Users can create appointments." on "public"."appointments";

drop policy "Users can delete their own appointments." on "public"."appointments";

drop policy "Users can update their own appointments." on "public"."appointments";

drop policy "Users can view their own appointments." on "public"."appointments";

drop policy "Allow all users to view time slots" on "public"."time_slots";

drop policy "Allow service_role to manage time slots" on "public"."time_slots";

drop policy "Users can create vehicles." on "public"."vehicles";

drop policy "Users can delete their own vehicles." on "public"."vehicles";

drop policy "Users can update their own vehicles." on "public"."vehicles";

drop policy "Users can view their own vehicles." on "public"."vehicles";

alter table "public"."time_slots" drop constraint "time_slots_day_of_week_check";

alter table "public"."vehicles" drop constraint "vehicles_plate_key";

alter table "public"."appointments" drop constraint "appointments_vehicle_id_fkey";

drop index if exists "public"."vehicles_plate_key";


  create table "public"."profiles" (
    "id" uuid not null,
    "email" text,
    "first_name" text,
    "last_name" text,
    "phone" text,
    "address" text,
    "city" text,
    "state" text,
    "zip_code" text,
    "role" text default 'customer'::text,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."profiles" enable row level security;

alter table "public"."appointments" drop column "total_price";

alter table "public"."appointments" drop column "updated_at";

alter table "public"."appointments" add column "appointment_date" date;

alter table "public"."appointments" add column "end_time" timestamp with time zone not null default timezone('utc'::text, now());

alter table "public"."appointments" add column "start_time" timestamp with time zone not null default timezone('utc'::text, now());

alter table "public"."appointments" alter column "appointment_time" drop not null;

alter table "public"."appointments" alter column "appointment_time" set data type time without time zone using "appointment_time"::time without time zone;

alter table "public"."appointments" alter column "created_at" set default timezone('utc'::text, now());

alter table "public"."appointments" alter column "created_at" set not null;

alter table "public"."appointments" alter column "id" drop default;

alter table "public"."appointments" alter column "id" add generated by default as identity;

alter table "public"."appointments" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."appointments" alter column "service_type" drop default;

alter table "public"."appointments" alter column "service_type" drop not null;

alter table "public"."appointments" alter column "status" drop not null;

alter table "public"."appointments" alter column "user_id" set not null;

alter table "public"."appointments" alter column "vehicle_id" set data type bigint using "vehicle_id"::bigint;

alter table "public"."time_slots" drop column "is_active";

alter table "public"."time_slots" add column "max_appointments" integer not null default 1;

alter table "public"."time_slots" alter column "created_at" set default timezone('utc'::text, now());

alter table "public"."time_slots" alter column "id" drop default;

alter table "public"."time_slots" alter column "id" add generated always as identity;

alter table "public"."time_slots" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."time_slots" disable row level security;

alter table "public"."vehicles" add column "is_default" boolean default false;

alter table "public"."vehicles" add column "license_plate" text;

alter table "public"."vehicles" add column "make" text not null;

alter table "public"."vehicles" add column "year" integer not null;

alter table "public"."vehicles" alter column "created_at" set default timezone('utc'::text, now());

alter table "public"."vehicles" alter column "created_at" set not null;

alter table "public"."vehicles" alter column "id" drop default;

alter table "public"."vehicles" alter column "id" add generated by default as identity;

alter table "public"."vehicles" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."vehicles" alter column "model" set not null;

alter table "public"."vehicles" alter column "plate" drop not null;

alter table "public"."vehicles" alter column "user_id" set not null;

drop sequence if exists "public"."appointments_id_seq";

drop sequence if exists "public"."time_slots_id_seq";

drop sequence if exists "public"."vehicles_id_seq";

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX time_slots_day_time_key ON public.time_slots USING btree (day_of_week, start_time, end_time);

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."time_slots" add constraint "time_slots_day_time_key" UNIQUE using index "time_slots_day_time_key";

alter table "public"."appointments" add constraint "appointments_vehicle_id_fkey" FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE SET NULL not valid;

alter table "public"."appointments" validate constraint "appointments_vehicle_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.create_appointment_with_check(p_user_id uuid, p_vehicle_id bigint, p_time_slot_id bigint, p_service_type text, p_special_instructions text, p_start_time timestamp with time zone, p_end_time timestamp with time zone)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_existing_count integer;
    v_new_appointment json;
BEGIN
    -- Check for existing appointments for the given start time
    SELECT count(*)
    INTO v_existing_count
    FROM public.appointments
    WHERE start_time = p_start_time AND status IN ('scheduled', 'confirmed');

    -- If an appointment exists, return an error
    IF v_existing_count > 0 THEN
        RETURN json_build_object('error', 'The selected time slot is no longer available');
    END IF;

    -- If the time slot is available, insert the new appointment
    INSERT INTO public.appointments(user_id, vehicle_id, time_slot_id, service_type, special_instructions, start_time, end_time, status)
    VALUES (p_user_id, p_vehicle_id, p_time_slot_id, p_service_type, p_special_instructions, p_start_time, p_end_time, 'scheduled')
    RETURNING json_build_object(
        'id', id,
        'user_id', user_id,
        'vehicle_id', vehicle_id,
        'time_slot_id', time_slot_id,
        'service_type', service_type,
        'special_instructions', special_instructions,
        'start_time', start_time,
        'end_time', end_time,
        'status', status,
        'created_at', created_at
    ) INTO v_new_appointment;

    -- Return the newly created appointment
    RETURN v_new_appointment;
END;
$function$
;

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


  create policy "Users can manage their own appointments."
  on "public"."appointments"
  as permissive
  for all
  to public
using ((auth.uid() = user_id));



  create policy "Public profiles are viewable by everyone."
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "Users can insert their own profile."
  on "public"."profiles"
  as permissive
  for insert
  to public
with check ((auth.uid() = id));



  create policy "Users can update own profile."
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id));



  create policy "Users can manage their own vehicles."
  on "public"."vehicles"
  as permissive
  for all
  to public
using ((auth.uid() = user_id));



